// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "<auto-generated />", Scope = "NamespaceAndDescendants", Target = "~N:Tasky.WebApp.Migrations")]
[assembly: SuppressMessage("Style", "IDE0161:Convert to file-scoped namespace", Justification = "<auto-generated />", Scope = "NamespaceAndDescendants", Target = "~N:Tasky.WebApp.Migrations")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "<auto-generated />", Scope = "NamespaceAndDescendants", Target = "~N:Tasky.WebApp.Migrations")]
